name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.RANDOMBITS_TOKEN }}
        with:
          source-files: 'dist/'
          destination-branch: main
          destination-username: 'nienow'
          destination-repository: 'randombits'
          destination-directory: 'content/print-schedule'
          commit-email: 'no-reply@randombits.dev'